Use [Master]
Go

Create DataBase USSArmy
Go

USE [USSArmy]
GO

/****** Object:  Table [dbo].[Soldiers]    Script Date: 2015-04-23 09:03:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Soldiers](
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [SoldierName] [varchar](50) NULL,
  [SoldierGrade] [int] NULL,
  CONSTRAINT [PK_Soldiers] PRIMARY KEY CLUSTERED 
(
  [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SoldierWeapons](
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [SoldierId] [int] NULL,
  [WeaponId] [int] NULL,
  [Position] [int] NULL,
 CONSTRAINT [PK_SoldierWeapons] PRIMARY KEY CLUSTERED 
(
  [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[WeaponCategories](
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [CategoryName] [varchar](25) NULL,
 CONSTRAINT [PK_WeaponCategories] PRIMARY KEY CLUSTERED 
(
  [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Weapons](
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [WeaponName] [varchar](50) NULL,
  [WeaponCategoryId] [int] NULL,
 CONSTRAINT [PK_Weapons] PRIMARY KEY CLUSTERED 
(
  [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SoldierWeapons]  WITH CHECK ADD  CONSTRAINT [FK_SoldierWeapons_Soldiers] FOREIGN KEY([SoldierId])
REFERENCES [dbo].[Soldiers] ([Id])
GO

ALTER TABLE [dbo].[SoldierWeapons] CHECK CONSTRAINT [FK_SoldierWeapons_Soldiers]
GO

ALTER TABLE [dbo].[SoldierWeapons]  WITH CHECK ADD  CONSTRAINT [FK_SoldierWeapons_Weapons] FOREIGN KEY([WeaponId])
REFERENCES [dbo].[Weapons] ([Id])
GO

ALTER TABLE [dbo].[SoldierWeapons] CHECK CONSTRAINT [FK_SoldierWeapons_Weapons]
GO

ALTER TABLE [dbo].[Weapons]  WITH CHECK ADD  CONSTRAINT [FK_Weapons_WeaponCategories] FOREIGN KEY([WeaponCategoryId])
REFERENCES [dbo].[WeaponCategories] ([Id])
GO

ALTER TABLE [dbo].[Weapons] CHECK CONSTRAINT [FK_Weapons_WeaponCategories]
GO

-- If the sysdiagrams table has not been created in this database, create it!
If Not Exists (Select * From INFORMATION_SCHEMA.TABLES Where TABLE_NAME = 'sysdiagrams')
Begin
  -- Create table script generated by Sql Server Management Studio
  -- _Assume_ this Is roughly equivalent to what Sql Server/Management Studio
  -- creates the first time you add a diagram to a 2008 database

  CREATE TABLE [dbo].[sysdiagrams](                        [name] [sysname] NOT Null
  ,[principal_id] [int] NOT Null
  ,[diagram_id] [int] IDENTITY(1,1) NOT Null
  ,[version] [int] Null
  ,[definition] [varbinary](max) Null
  ,PRIMARY KEY CLUSTERED
  ([diagram_id] ASC)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF)
  ,CONSTRAINT [UK_principal_name] UNIQUE NONCLUSTERED
  ([principal_id] ASC,[name] ASC)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF)
  )

  EXEC sys.sp_addextEndedproperty @name=N'microsoft_database_tools_support', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'sysdiagrams'

  Print '[sysdiagrams] table was created as it did not already exist'
End
Go

-- Target table will now exist, If it didn't before
Set NOCOUNT ON -- Hide (1 row affected) messages
Declare @newid INT
Declare @DiagramSuffix varchar(50)
 
Print 'Suffix diagram name with date, to ensure uniqueness'
Set @DiagramSuffix = ' ' + LEFT(CONVERT(VARCHAR(23), GETDATE(), 121), 16)
 
Print 'Create row for new diagram'
Begin Try
  Print 'Write diagram USSArmy into new row (and get [diagram_id])'

  INSERT INTO sysdiagrams ([name], [principal_id], [version], [definition]) VALUES ('USSArmy'+@DiagramSuffix, 1, 1, 0x)
  Set @newid = SCOPE_IDENTITY()
End Try
Begin Catch
  Print 'XxXxX ' + Error_Message() + ' XxXxX'
  Print 'XxXxX End Tool_ScriptDiagram2008 -- fix the error before running again XxXxX'
  Return
End Catch
 
Print 'Now add all the binary data…'
Begin TRY
  Update sysdiagrams Set [definition] .Write ( 0XD0CF11E0A1B11AE1000000000000000000000000000000003E000300FEFF0900, Null, 0) Where diagram_id = @newid -- index:1
  Update sysdiagrams Set [definition] .Write ( 0X0600000000000000000000000100000001000000000000000010000002000000, Null, 0) Where diagram_id = @newid -- index:33
  Update sysdiagrams Set [definition] .Write ( 0X01000000FEFFFFFF0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:65
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:97
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:129
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:161
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:193
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:225
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:257
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:289
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:321
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:353
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:385
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:417
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:449
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:481
  Update sysdiagrams Set [definition] .Write ( 0XFDFFFFFF0C000000FEFFFFFF0400000005000000060000000700000008000000, Null, 0) Where diagram_id = @newid -- index:513
  Update sysdiagrams Set [definition] .Write ( 0X090000000A0000000B0000000D000000FEFFFFFF0E0000000F00000010000000, Null, 0) Where diagram_id = @newid -- index:545
  Update sysdiagrams Set [definition] .Write ( 0X110000001200000013000000FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:577
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:609
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:641
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:673
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:705
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:737
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:769
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:801
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:833
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:865
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:897
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:929
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:961
  Update sysdiagrams Set [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:993
  Update sysdiagrams Set [definition] .Write ( 0X52006F006F007400200045006E00740072007900000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1025
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1057
  Update sysdiagrams Set [definition] .Write ( 0X16000500FFFFFFFFFFFFFFFF0200000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1089
  Update sysdiagrams Set [definition] .Write ( 0X000000000000000000000000609C4869C57DD00103000000C01F000000000000, Null, 0) Where diagram_id = @newid -- index:1121
  Update sysdiagrams Set [definition] .Write ( 0X6600000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1153
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1185
  Update sysdiagrams Set [definition] .Write ( 0X04000201FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1217
  Update sysdiagrams Set [definition] .Write ( 0X000000000000000000000000000000000000000000000000CE03000000000000, Null, 0) Where diagram_id = @newid -- index:1249
  Update sysdiagrams Set [definition] .Write ( 0X6F00000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1281
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1313
  Update sysdiagrams Set [definition] .Write ( 0X040002010100000004000000FFFFFFFF00000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1345
  Update sysdiagrams Set [definition] .Write ( 0X000000000000000000000000000000000000000010000000DD0C000000000000, Null, 0) Where diagram_id = @newid -- index:1377
  Update sysdiagrams Set [definition] .Write ( 0X010043006F006D0070004F0062006A0000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1409
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1441
  Update sysdiagrams Set [definition] .Write ( 0X12000201FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:1473
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000440000005F00000000000000, Null, 0) Where diagram_id = @newid -- index:1505
  Update sysdiagrams Set [definition] .Write ( 0X0100000002000000030000000400000005000000060000000700000008000000, Null, 0) Where diagram_id = @newid -- index:1537
  Update sysdiagrams Set [definition] .Write ( 0X090000000A0000000B0000000C0000000D0000000E0000000F000000FEFFFFFF, Null, 0) Where diagram_id = @newid -- index:1569
  Update sysdiagrams Set [definition] .Write ( 0X1100000012000000130000001400000015000000160000001700000018000000, Null, 0) Where diagram_id = @newid -- index:1601
  Update sysdiagrams Set [definition] .Write ( 0X190000001A0000001B0000001C0000001D0000001E0000001F00000020000000, Null, 0) Where diagram_id = @newid -- index:1633
  Update sysdiagrams Set [definition] .Write ( 0X2100000022000000230000002400000025000000260000002700000028000000, Null, 0) Where diagram_id = @newid -- index:1665
  Update sysdiagrams Set [definition] .Write ( 0X290000002A0000002B0000002C0000002D0000002E0000002F00000030000000, Null, 0) Where diagram_id = @newid -- index:1697
  Update sysdiagrams Set [definition] .Write ( 0X3100000032000000330000003400000035000000360000003700000038000000, Null, 0) Where diagram_id = @newid -- index:1729
  Update sysdiagrams Set [definition] .Write ( 0X390000003A0000003B0000003C0000003D0000003E0000003F00000040000000, Null, 0) Where diagram_id = @newid -- index:1761
  Update sysdiagrams Set [definition] .Write ( 0X410000004200000043000000FEFFFFFF45000000FEFFFFFF4700000048000000, Null, 0) Where diagram_id = @newid -- index:1793
  Update sysdiagrams Set [definition] .Write ( 0X490000004A0000004B0000004C0000004D0000004E0000004F00000050000000, Null, 0) Where diagram_id = @newid -- index:1825
  Update sysdiagrams Set [definition] .Write ( 0X5100000052000000530000005400000055000000560000005700000058000000, Null, 0) Where diagram_id = @newid -- index:1857
  Update sysdiagrams Set [definition] .Write ( 0X590000005A0000005B0000005C0000005D0000005E0000005F00000060000000, Null, 0) Where diagram_id = @newid -- index:1889
  Update sysdiagrams Set [definition] .Write ( 0X6100000062000000630000006400000065000000660000006700000068000000, Null, 0) Where diagram_id = @newid -- index:1921
  Update sysdiagrams Set [definition] .Write ( 0X690000006A0000006B0000006C0000006D0000006E0000006F00000070000000, Null, 0) Where diagram_id = @newid -- index:1953
  Update sysdiagrams Set [definition] .Write ( 0XFEFFFFFFFEFFFFFF730000007400000075000000760000007700000078000000, Null, 0) Where diagram_id = @newid -- index:1985
  Update sysdiagrams Set [definition] .Write ( 0X790000007A0000007B0000007C0000007D000000FEFFFFFFFEFFFFFFFFFFFFFF, Null, 0) Where diagram_id = @newid -- index:2017
  Update sysdiagrams Set [definition] .Write ( 0X000428000A0E100C050000800A0000000F00FFFF0A000000007D000014400000, Null, 0) Where diagram_id = @newid -- index:2049
  Update sysdiagrams Set [definition] .Write ( 0X393800005F5D0000F04E0000DE805B10F195D011B0A000AA00BDCB5C00000800, Null, 0) Where diagram_id = @newid -- index:2081
  Update sysdiagrams Set [definition] .Write ( 0X30000000000200000300000038002B00000009000000D9E6B0E91C81D011AD51, Null, 0) Where diagram_id = @newid -- index:2113
  Update sysdiagrams Set [definition] .Write ( 0X00A0C90F5739F43B7F847F61C74385352986E1D552F8A0327DB2D86295428D98, Null, 0) Where diagram_id = @newid -- index:2145
  Update sysdiagrams Set [definition] .Write ( 0X273C25A2DA2D00002C0043200000000000000000000053444DD2011FD1118E63, Null, 0) Where diagram_id = @newid -- index:2177
  Update sysdiagrams Set [definition] .Write ( 0X006097D2DF4834C9D2777977D811907000065B840D9C00002C00432000000000, Null, 0) Where diagram_id = @newid -- index:2209
  Update sysdiagrams Set [definition] .Write ( 0X00000000000051444DD2011FD1118E63006097D2DF4834C9D2777977D8119070, Null, 0) Where diagram_id = @newid -- index:2241
  Update sysdiagrams Set [definition] .Write ( 0X00065B840D9C0A000000E0020000008A010000003000A5090000070000800100, Null, 0) Where diagram_id = @newid -- index:2273
  Update sysdiagrams Set [definition] .Write ( 0X0000A202000000800000080000805363684772696400D0200000EE020000536F, Null, 0) Where diagram_id = @newid -- index:2305
  Update sysdiagrams Set [definition] .Write ( 0X6C646965727300003800A50900000700008002000000AE020000008000000E00, Null, 0) Where diagram_id = @newid -- index:2337
  Update sysdiagrams Set [definition] .Write ( 0X00805363684772696473C2010000C2010000536F6C64696572576561706F6E73, Null, 0) Where diagram_id = @newid -- index:2369
  Update sysdiagrams Set [definition] .Write ( 0X000000003800A50900000700008003000000B202000000800000100000805363, Null, 0) Where diagram_id = @newid -- index:2401
  Update sysdiagrams Set [definition] .Write ( 0X684772696473D02000004C1D0000576561706F6E43617465676F726965730000, Null, 0) Where diagram_id = @newid -- index:2433
  Update sysdiagrams Set [definition] .Write ( 0X3000A50900000700008004000000A00200000080000007000080536368477269, Null, 0) Where diagram_id = @newid -- index:2465
  Update sysdiagrams Set [definition] .Write ( 0X6473C2010000B61C0000576561706F6E737300007800A5090000070000800500, Null, 0) Where diagram_id = @newid -- index:2497
  Update sysdiagrams Set [definition] .Write ( 0X0000620000000180000050000080436F6E74726F6C73D7170000C90700005265, Null, 0) Where diagram_id = @newid -- index:2529
  Update sysdiagrams Set [definition] .Write ( 0X6C6174696F6E20ABA0464B5F536F6C64696572576561706F6E735F536F6C6469, Null, 0) Where diagram_id = @newid -- index:2561
  Update sysdiagrams Set [definition] .Write ( 0X657273A0BB20656E74726520ABA0536F6C6469657273A0BB20657420ABA0536F, Null, 0) Where diagram_id = @newid -- index:2593
  Update sysdiagrams Set [definition] .Write ( 0X6C64696572576561706F6E73A0BB00002800B501000007000080060000003100, Null, 0) Where diagram_id = @newid -- index:2625
  Update sysdiagrams Set [definition] .Write ( 0X00006700000002800000436F6E74726F6C73A70E00005907000000007800A509, Null, 0) Where diagram_id = @newid -- index:2657
  Update sysdiagrams Set [definition] .Write ( 0X0000070000800700000052000000018000004E000080436F6E74726F6C73ED01, Null, 0) Where diagram_id = @newid -- index:2689
  Update sysdiagrams Set [definition] .Write ( 0X00006E0E000052656C6174696F6E20ABA0464B5F536F6C64696572576561706F, Null, 0) Where diagram_id = @newid -- index:2721
  Update sysdiagrams Set [definition] .Write ( 0X6E735F576561706F6E73A0BB20656E74726520ABA0576561706F6E73A0BB2065, Null, 0) Where diagram_id = @newid -- index:2753
  Update sysdiagrams Set [definition] .Write ( 0X7420ABA0536F6C64696572576561706F6E73A0BBA0BB00002800B50100000700, Null, 0) Where diagram_id = @newid -- index:2785
  Update sysdiagrams Set [definition] .Write ( 0X008008000000310000006500000002800000436F6E74726F6C73330400004316, Null, 0) Where diagram_id = @newid -- index:2817
  Update sysdiagrams Set [definition] .Write ( 0X000000007C00A50900000700008009000000520000000180000052000080436F, Null, 0) Where diagram_id = @newid -- index:2849
  Update sysdiagrams Set [definition] .Write ( 0X6E74726F6C73D71700002722000052656C6174696F6E20ABA0464B5F57656170, Null, 0) Where diagram_id = @newid -- index:2881
  Update sysdiagrams Set [definition] .Write ( 0X6F6E735F576561706F6E43617465676F72696573A0BB20656E74726520ABA057, Null, 0) Where diagram_id = @newid -- index:2913
  Update sysdiagrams Set [definition] .Write ( 0X6561706F6E43617465676F72696573A0BB20657420ABA0576561706F6E73A0BB, Null, 0) Where diagram_id = @newid -- index:2945
  Update sysdiagrams Set [definition] .Write ( 0X6E0000002800B5010000070000800A000000310000006900000002800000436F, Null, 0) Where diagram_id = @newid -- index:2977
  Update sysdiagrams Set [definition] .Write ( 0X6E74726F6C73D7130000B7210000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:3009
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:3041
  Update sysdiagrams Set [definition] .Write ( 0X214334120800000041170000EC0C000078563412070000001401000053006F00, Null, 0) Where diagram_id = @newid -- index:3073
  Update sysdiagrams Set [definition] .Write ( 0X6C00640069006500720073000000000000000000006083400000000000001040, Null, 0) Where diagram_id = @newid -- index:3105
  Update sysdiagrams Set [definition] .Write ( 0X0100000000000000000000000E00000005000000180100000000000000000000, Null, 0) Where diagram_id = @newid -- index:3137
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000F80000000000000005000000000000000000000002000000, Null, 0) Where diagram_id = @newid -- index:3169
  Update sysdiagrams Set [definition] .Write ( 0X0000000000608340000000000000000000000000006083400000000000000040, Null, 0) Where diagram_id = @newid -- index:3201
  Update sysdiagrams Set [definition] .Write ( 0X0400000020000000300000000000000000000000005083400000000000001040, Null, 0) Where diagram_id = @newid -- index:3233
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000040000000000000004000000000000000000100000000000000, Null, 0) Where diagram_id = @newid -- index:3265
  Update sysdiagrams Set [definition] .Write ( 0X0500000000000000400000000100000000000000000000400000000000001040, Null, 0) Where diagram_id = @newid -- index:3297
  Update sysdiagrams Set [definition] .Write ( 0X0400000020000000200000000000000000000000010000000500000054000000, Null, 0) Where diagram_id = @newid -- index:3329
  Update sysdiagrams Set [definition] .Write ( 0X2C0000002C0000002C000000340000000000000000000000A729000039160000, Null, 0) Where diagram_id = @newid -- index:3361
  Update sysdiagrams Set [definition] .Write ( 0X000000002D010000070000000C000000070000001C010000F708000053070000, Null, 0) Where diagram_id = @newid -- index:3393
  Update sysdiagrams Set [definition] .Write ( 0X390300000B040000D0020000DD04000018060000A203000018060000BC070000, Null, 0) Where diagram_id = @newid -- index:3425
  Update sysdiagrams Set [definition] .Write ( 0X46050000000000000100000041170000EC0C0000000000000300000003000000, Null, 0) Where diagram_id = @newid -- index:3457
  Update sysdiagrams Set [definition] .Write ( 0X02000000020000001C010000E60A00000000000001000000F21300004E060000, Null, 0) Where diagram_id = @newid -- index:3489
  Update sysdiagrams Set [definition] .Write ( 0X00000000010000000100000002000000020000001C010000F708000001000000, Null, 0) Where diagram_id = @newid -- index:3521
  Update sysdiagrams Set [definition] .Write ( 0X00000000F2130000080400000000000000000000000000000200000002000000, Null, 0) Where diagram_id = @newid -- index:3553
  Update sysdiagrams Set [definition] .Write ( 0X1C010000F7080000000000000000000055320000DD2300000000000000000000, Null, 0) Where diagram_id = @newid -- index:3585
  Update sysdiagrams Set [definition] .Write ( 0X0D00000004000000040000001C010000F70800009B0A00008106000078563412, Null, 0) Where diagram_id = @newid -- index:3617
  Update sysdiagrams Set [definition] .Write ( 0X040000005A00000001000000010000000B000000000000000100000002000000, Null, 0) Where diagram_id = @newid -- index:3649
  Update sysdiagrams Set [definition] .Write ( 0X030000000400000005000000060000000700000008000000090000000A000000, Null, 0) Where diagram_id = @newid -- index:3681
  Update sysdiagrams Set [definition] .Write ( 0X04000000640062006F0000000900000053006F006C0064006900650072007300, Null, 0) Where diagram_id = @newid -- index:3713
  Update sysdiagrams Set [definition] .Write ( 0X0000214334120800000041170000670F00007856341207000000140100005300, Null, 0) Where diagram_id = @newid -- index:3745
  Update sysdiagrams Set [definition] .Write ( 0X6F006C00640069006500720057006500610070006F006E007300000020005600, Null, 0) Where diagram_id = @newid -- index:3777
  Update sysdiagrams Set [definition] .Write ( 0X65007200730069006F006E003D0032002E0030002E0030002E0030002C002000, Null, 0) Where diagram_id = @newid -- index:3809
  Update sysdiagrams Set [definition] .Write ( 0X430075006C0074007500720065003D006E00650075007400720061006C002C00, Null, 0) Where diagram_id = @newid -- index:3841
  Update sysdiagrams Set [definition] .Write ( 0X20005000750062006C00690063004B006500790054006F006B0065006E003D00, Null, 0) Where diagram_id = @newid -- index:3873
  Update sysdiagrams Set [definition] .Write ( 0X6200300033006600350066003700660031003100640035003000610033006100, Null, 0) Where diagram_id = @newid -- index:3905
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:3937
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:3969
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000001000000050000005400, Null, 0) Where diagram_id = @newid -- index:4001
  Update sysdiagrams Set [definition] .Write ( 0X00002C0000002C0000002C000000340000000000000000000000A72900003916, Null, 0) Where diagram_id = @newid -- index:4033
  Update sysdiagrams Set [definition] .Write ( 0X0000000000002D010000070000000C000000070000001C010000F70800005307, Null, 0) Where diagram_id = @newid -- index:4065
  Update sysdiagrams Set [definition] .Write ( 0X0000390300000B040000D0020000DD04000018060000A203000018060000BC07, Null, 0) Where diagram_id = @newid -- index:4097
  Update sysdiagrams Set [definition] .Write ( 0X000046050000000000000100000041170000670F000000000000040000000400, Null, 0) Where diagram_id = @newid -- index:4129
  Update sysdiagrams Set [definition] .Write ( 0X000002000000020000001C010000E60A00000000000001000000F21300004E06, Null, 0) Where diagram_id = @newid -- index:4161
  Update sysdiagrams Set [definition] .Write ( 0X000000000000010000000100000002000000020000001C010000F70800000100, Null, 0) Where diagram_id = @newid -- index:4193
  Update sysdiagrams Set [definition] .Write ( 0X000000000000F213000008040000000000000000000000000000020000000200, Null, 0) Where diagram_id = @newid -- index:4225
  Update sysdiagrams Set [definition] .Write ( 0X00001C010000F7080000000000000000000055320000DD230000000000000000, Null, 0) Where diagram_id = @newid -- index:4257
  Update sysdiagrams Set [definition] .Write ( 0X00000D00000004000000040000001C010000F70800009B0A0000810600007856, Null, 0) Where diagram_id = @newid -- index:4289
  Update sysdiagrams Set [definition] .Write ( 0X3412040000006600000001000000010000000B00000000000000010000000200, Null, 0) Where diagram_id = @newid -- index:4321
  Update sysdiagrams Set [definition] .Write ( 0X0000030000000400000005000000060000000700000008000000090000000A00, Null, 0) Where diagram_id = @newid -- index:4353
  Update sysdiagrams Set [definition] .Write ( 0X000004000000640062006F0000000F00000053006F006C006400690065007200, Null, 0) Where diagram_id = @newid -- index:4385
  Update sysdiagrams Set [definition] .Write ( 0X57006500610070006F006E0073000000214334120800000041170000710A0000, Null, 0) Where diagram_id = @newid -- index:4417
  Update sysdiagrams Set [definition] .Write ( 0X78563412070000001401000057006500610070006F006E004300610074006500, Null, 0) Where diagram_id = @newid -- index:4449
  Update sysdiagrams Set [definition] .Write ( 0X67006F007200690065007300000072006D0073002C0020005600650072007300, Null, 0) Where diagram_id = @newid -- index:4481
  Update sysdiagrams Set [definition] .Write ( 0X69006F006E003D0034002E0030002E0030002E0030002C002000430075006C00, Null, 0) Where diagram_id = @newid -- index:4513
  Update sysdiagrams Set [definition] .Write ( 0X74007500720065003D006E00650075007400720061006C002C00200050007500, Null, 0) Where diagram_id = @newid -- index:4545
  Update sysdiagrams Set [definition] .Write ( 0X62006C00690063004B006500790054006F006B0065006E003D00620037003700, Null, 0) Where diagram_id = @newid -- index:4577
  Update sysdiagrams Set [definition] .Write ( 0X6100350063003500360031003900330034006500300038003900000000000000, Null, 0) Where diagram_id = @newid -- index:4609
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:4641
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:4673
  Update sysdiagrams Set [definition] .Write ( 0X000000000100000005000000540000002C0000002C0000002C00000034000000, Null, 0) Where diagram_id = @newid -- index:4705
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000A729000039160000000000002D010000070000000C000000, Null, 0) Where diagram_id = @newid -- index:4737
  Update sysdiagrams Set [definition] .Write ( 0X070000001C010000F708000053070000390300000B040000D0020000DD040000, Null, 0) Where diagram_id = @newid -- index:4769
  Update sysdiagrams Set [definition] .Write ( 0X18060000A203000018060000BC07000046050000000000000100000041170000, Null, 0) Where diagram_id = @newid -- index:4801
  Update sysdiagrams Set [definition] .Write ( 0X710A000000000000020000000200000002000000020000001C010000E60A0000, Null, 0) Where diagram_id = @newid -- index:4833
  Update sysdiagrams Set [definition] .Write ( 0X0000000001000000F21300004E06000000000000010000000100000002000000, Null, 0) Where diagram_id = @newid -- index:4865
  Update sysdiagrams Set [definition] .Write ( 0X020000001C010000F70800000100000000000000F21300000804000000000000, Null, 0) Where diagram_id = @newid -- index:4897
  Update sysdiagrams Set [definition] .Write ( 0X000000000000000002000000020000001C010000F70800000000000000000000, Null, 0) Where diagram_id = @newid -- index:4929
  Update sysdiagrams Set [definition] .Write ( 0X55320000DD23000000000000000000000D00000004000000040000001C010000, Null, 0) Where diagram_id = @newid -- index:4961
  Update sysdiagrams Set [definition] .Write ( 0XF70800009B0A00008106000078563412040000006A0000000100000001000000, Null, 0) Where diagram_id = @newid -- index:4993
  Update sysdiagrams Set [definition] .Write ( 0X0B00000000000000010000000200000003000000040000000500000006000000, Null, 0) Where diagram_id = @newid -- index:5025
  Update sysdiagrams Set [definition] .Write ( 0X0700000008000000090000000A00000004000000640062006F00000011000000, Null, 0) Where diagram_id = @newid -- index:5057
  Update sysdiagrams Set [definition] .Write ( 0X57006500610070006F006E00430061007400650067006F007200690065007300, Null, 0) Where diagram_id = @newid -- index:5089
  Update sysdiagrams Set [definition] .Write ( 0X0000214334120800000041170000EC0C00007856341207000000140100005700, Null, 0) Where diagram_id = @newid -- index:5121
  Update sysdiagrams Set [definition] .Write ( 0X6500610070006F006E007300000069006E0064006F00770073002E0046006F00, Null, 0) Where diagram_id = @newid -- index:5153
  Update sysdiagrams Set [definition] .Write ( 0X72006D0073002C002000560065007200730069006F006E003D0034002E003000, Null, 0) Where diagram_id = @newid -- index:5185
  Update sysdiagrams Set [definition] .Write ( 0X2E0030002E0030002C002000430075006C0074007500720065003D006E006500, Null, 0) Where diagram_id = @newid -- index:5217
  Update sysdiagrams Set [definition] .Write ( 0X75007400720061006C002C0020005000750062006C00690063004B0065007900, Null, 0) Where diagram_id = @newid -- index:5249
  Update sysdiagrams Set [definition] .Write ( 0X54006F006B0065006E003D006200370037006100350063003500360031003900, Null, 0) Where diagram_id = @newid -- index:5281
  Update sysdiagrams Set [definition] .Write ( 0X3300340065003000380039000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:5313
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:5345
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000001000000050000005400, Null, 0) Where diagram_id = @newid -- index:5377
  Update sysdiagrams Set [definition] .Write ( 0X00002C0000002C0000002C000000340000000000000000000000A72900003916, Null, 0) Where diagram_id = @newid -- index:5409
  Update sysdiagrams Set [definition] .Write ( 0X0000000000002D010000070000000C000000070000001C010000F70800005307, Null, 0) Where diagram_id = @newid -- index:5441
  Update sysdiagrams Set [definition] .Write ( 0X0000390300000B040000D0020000DD04000018060000A203000018060000BC07, Null, 0) Where diagram_id = @newid -- index:5473
  Update sysdiagrams Set [definition] .Write ( 0X000046050000000000000100000041170000EC0C000000000000030000000300, Null, 0) Where diagram_id = @newid -- index:5505
  Update sysdiagrams Set [definition] .Write ( 0X000002000000020000001C010000E60A00000000000001000000F21300004E06, Null, 0) Where diagram_id = @newid -- index:5537
  Update sysdiagrams Set [definition] .Write ( 0X000000000000010000000100000002000000020000001C010000F70800000100, Null, 0) Where diagram_id = @newid -- index:5569
  Update sysdiagrams Set [definition] .Write ( 0X000000000000F213000008040000000000000000000000000000020000000200, Null, 0) Where diagram_id = @newid -- index:5601
  Update sysdiagrams Set [definition] .Write ( 0X00001C010000F7080000000000000000000055320000DD230000000000000000, Null, 0) Where diagram_id = @newid -- index:5633
  Update sysdiagrams Set [definition] .Write ( 0X00000D00000004000000040000001C010000F70800009B0A0000810600007856, Null, 0) Where diagram_id = @newid -- index:5665
  Update sysdiagrams Set [definition] .Write ( 0X3412040000005800000001000000010000000B00000000000000010000000200, Null, 0) Where diagram_id = @newid -- index:5697
  Update sysdiagrams Set [definition] .Write ( 0X0000030000000400000005000000060000000700000008000000090000000A00, Null, 0) Where diagram_id = @newid -- index:5729
  Update sysdiagrams Set [definition] .Write ( 0X000004000000640062006F0000000800000057006500610070006F006E007300, Null, 0) Where diagram_id = @newid -- index:5761
  Update sysdiagrams Set [definition] .Write ( 0X000004000B00D020000060090000CB1D000060090000CB1D0000600900000319, Null, 0) Where diagram_id = @newid -- index:5793
  Update sysdiagrams Set [definition] .Write ( 0X0000600900000000000002000000F0F0F0000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:5825
  Update sysdiagrams Set [definition] .Write ( 0X0000010000000600000000000000A70E0000590700008B0F0000580100001B00, Null, 0) Where diagram_id = @newid -- index:5857
  Update sysdiagrams Set [definition] .Write ( 0X00000100000200008B0F00005801000002000000000005000080080000800100, Null, 0) Where diagram_id = @newid -- index:5889
  Update sysdiagrams Set [definition] .Write ( 0X0000150001000000900144420100065461686F6D611A0046004B005F0053006F, Null, 0) Where diagram_id = @newid -- index:5921
  Update sysdiagrams Set [definition] .Write ( 0X006C00640069006500720057006500610070006F006E0073005F0053006F006C, Null, 0) Where diagram_id = @newid -- index:5953
  Update sysdiagrams Set [definition] .Write ( 0X006400690065007200730002000B0084030000B61C0000840300002911000000, Null, 0) Where diagram_id = @newid -- index:5985
  Update sysdiagrams Set [definition] .Write ( 0X00000002000000F0F0F000000000000000000000000000000000000100000008, Null, 0) Where diagram_id = @newid -- index:6017
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000033040000431600007210000058010000320000000100000200, Null, 0) Where diagram_id = @newid -- index:6049
  Update sysdiagrams Set [definition] .Write ( 0X007210000058010000020000000000FFFFFF0008000080010000001500010000, Null, 0) Where diagram_id = @newid -- index:6081
  Update sysdiagrams Set [definition] .Write ( 0X00900144420100065461686F6D61190046004B005F0053006F006C0064006900, Null, 0) Where diagram_id = @newid -- index:6113
  Update sysdiagrams Set [definition] .Write ( 0X6500720057006500610070006F006E0073005F0057006500610070006F006E00, Null, 0) Where diagram_id = @newid -- index:6145
  Update sysdiagrams Set [definition] .Write ( 0X730002000B00D0200000BE23000003190000BE2300000000000002000000F0F0, Null, 0) Where diagram_id = @newid -- index:6177
  Update sysdiagrams Set [definition] .Write ( 0XF00000000000000000000000000000000000010000000A00000000000000D713, Null, 0) Where diagram_id = @newid -- index:6209
  Update sysdiagrams Set [definition] .Write ( 0X0000B72100002312000058010000320000000100000200002312000058010000, Null, 0) Where diagram_id = @newid -- index:6241
  Update sysdiagrams Set [definition] .Write ( 0X020000000000FFFFFF0008000080010000001500010000009001444201000654, Null, 0) Where diagram_id = @newid -- index:6273
  Update sysdiagrams Set [definition] .Write ( 0X61686F6D611B0046004B005F0057006500610070006F006E0073005F00570065, Null, 0) Where diagram_id = @newid -- index:6305
  Update sysdiagrams Set [definition] .Write ( 0X00610070006F006E00430061007400650067006F007200690065007300000000, Null, 0) Where diagram_id = @newid -- index:6337
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6369
  Update sysdiagrams Set [definition] .Write ( 0X0100FEFF030A0000FFFFFFFF0000000000000000000000000000000017000000, Null, 0) Where diagram_id = @newid -- index:6401
  Update sysdiagrams Set [definition] .Write ( 0X4D6963726F736F66742044445320466F726D20322E300010000000456D626564, Null, 0) Where diagram_id = @newid -- index:6433
  Update sysdiagrams Set [definition] .Write ( 0X646564204F626A6563740000000000F439B27100000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6465
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6497
  Update sysdiagrams Set [definition] .Write ( 0X0C00000000000000000000000100260000007300630068005F006C0061006200, Null, 0) Where diagram_id = @newid -- index:6529
  Update sysdiagrams Set [definition] .Write ( 0X65006C0073005F00760069007300690062006C0065000000010000000B000000, Null, 0) Where diagram_id = @newid -- index:6561
  Update sysdiagrams Set [definition] .Write ( 0X1E00000000000000000000000000000000000000640000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6593
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000010000000100000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6625
  Update sysdiagrams Set [definition] .Write ( 0X0300440064007300530074007200650061006D00000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6657
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6689
  Update sysdiagrams Set [definition] .Write ( 0X160002000300000006000000FFFFFFFF00000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6721
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000460000008F0A000000000000, Null, 0) Where diagram_id = @newid -- index:6753
  Update sysdiagrams Set [definition] .Write ( 0X53006300680065006D0061002000550044005600200044006500660061007500, Null, 0) Where diagram_id = @newid -- index:6785
  Update sysdiagrams Set [definition] .Write ( 0X6C00740000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6817
  Update sysdiagrams Set [definition] .Write ( 0X26000200FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6849
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000710000001600000000000000, Null, 0) Where diagram_id = @newid -- index:6881
  Update sysdiagrams Set [definition] .Write ( 0X440053005200450046002D0053004300480045004D0041002D0043004F004E00, Null, 0) Where diagram_id = @newid -- index:6913
  Update sysdiagrams Set [definition] .Write ( 0X540045004E005400530000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6945
  Update sysdiagrams Set [definition] .Write ( 0X2C0002010500000007000000FFFFFFFF00000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:6977
  Update sysdiagrams Set [definition] .Write ( 0X000000000000000000000000000000000000000072000000F002000000000000, Null, 0) Where diagram_id = @newid -- index:7009
  Update sysdiagrams Set [definition] .Write ( 0X53006300680065006D0061002000550044005600200044006500660061007500, Null, 0) Where diagram_id = @newid -- index:7041
  Update sysdiagrams Set [definition] .Write ( 0X6C007400200050006F0073007400200056003600000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:7073
  Update sysdiagrams Set [definition] .Write ( 0X36000200FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:7105
  Update sysdiagrams Set [definition] .Write ( 0X00000000000000000000000000000000000000007E0000001200000000000000, Null, 0) Where diagram_id = @newid -- index:7137
  Update sysdiagrams Set [definition] .Write ( 0X000000000000D002000006002800000041006300740069007600650054006100, Null, 0) Where diagram_id = @newid -- index:7169
  Update sysdiagrams Set [definition] .Write ( 0X62006C00650056006900650077004D006F006400650000000100000008000400, Null, 0) Where diagram_id = @newid -- index:7201
  Update sysdiagrams Set [definition] .Write ( 0X000031000000200000005400610062006C00650056006900650077004D006F00, Null, 0) Where diagram_id = @newid -- index:7233
  Update sysdiagrams Set [definition] .Write ( 0X640065003A00300000000100000008003A00000034002C0030002C0032003800, Null, 0) Where diagram_id = @newid -- index:7265
  Update sysdiagrams Set [definition] .Write ( 0X34002C0030002C0032003200390035002C0031002C0031003800370035002C00, Null, 0) Where diagram_id = @newid -- index:7297
  Update sysdiagrams Set [definition] .Write ( 0X35002C0031003200340035000000200000005400610062006C00650056006900, Null, 0) Where diagram_id = @newid -- index:7329
  Update sysdiagrams Set [definition] .Write ( 0X650077004D006F00640065003A00310000000100000008001E00000032002C00, Null, 0) Where diagram_id = @newid -- index:7361
  Update sysdiagrams Set [definition] .Write ( 0X30002C003200380034002C0030002C0032003700390030000000200000005400, Null, 0) Where diagram_id = @newid -- index:7393
  Update sysdiagrams Set [definition] .Write ( 0X610062006C00650056006900650077004D006F00640065003A00320000000100, Null, 0) Where diagram_id = @newid -- index:7425
  Update sysdiagrams Set [definition] .Write ( 0X000008001E00000032002C0030002C003200380034002C0030002C0032003200, Null, 0) Where diagram_id = @newid -- index:7457
  Update sysdiagrams Set [definition] .Write ( 0X390035000000200000005400610062006C00650056006900650077004D006F00, Null, 0) Where diagram_id = @newid -- index:7489
  Update sysdiagrams Set [definition] .Write ( 0X640065003A00330000000100000008001E00000032002C0030002C0032003800, Null, 0) Where diagram_id = @newid -- index:7521
  Update sysdiagrams Set [definition] .Write ( 0X34002C0030002C0032003200390035000000200000005400610062006C006500, Null, 0) Where diagram_id = @newid -- index:7553
  Update sysdiagrams Set [definition] .Write ( 0X56006900650077004D006F00640065003A00340000000100000008003E000000, Null, 0) Where diagram_id = @newid -- index:7585
  Update sysdiagrams Set [definition] .Write ( 0X34002C0030002C003200380034002C0030002C0032003200390035002C003100, Null, 0) Where diagram_id = @newid -- index:7617
  Update sysdiagrams Set [definition] .Write ( 0X32002C0032003700310035002C00310031002C00310036003600350000000200, Null, 0) Where diagram_id = @newid -- index:7649
  Update sysdiagrams Set [definition] .Write ( 0X00000200000000000000000000000000000000000000D0020000060028000000, Null, 0) Where diagram_id = @newid -- index:7681
  Update sysdiagrams Set [definition] .Write ( 0X4100630074006900760065005400610062006C00650056006900650077004D00, Null, 0) Where diagram_id = @newid -- index:7713
  Update sysdiagrams Set [definition] .Write ( 0X6F00640065000000010000000800040000003100000020000000540061006200, Null, 0) Where diagram_id = @newid -- index:7745
  Update sysdiagrams Set [definition] .Write ( 0X6C00650056006900650077004D006F00640065003A0030000000010000000800, Null, 0) Where diagram_id = @newid -- index:7777
  Update sysdiagrams Set [definition] .Write ( 0X3A00000034002C0030002C003200380034002C0030002C003200320039003500, Null, 0) Where diagram_id = @newid -- index:7809
  Update sysdiagrams Set [definition] .Write ( 0X2C0031002C0031003800370035002C0035002C00310032003400350000002000, Null, 0) Where diagram_id = @newid -- index:7841
  Update sysdiagrams Set [definition] .Write ( 0X00005400610062006C00650056006900650077004D006F00640065003A003100, Null, 0) Where diagram_id = @newid -- index:7873
  Update sysdiagrams Set [definition] .Write ( 0X00000100000008001E00000032002C0030002C003200380034002C0030002C00, Null, 0) Where diagram_id = @newid -- index:7905
  Update sysdiagrams Set [definition] .Write ( 0X32003700390030000000200000005400610062006C0065005600690065007700, Null, 0) Where diagram_id = @newid -- index:7937
  Update sysdiagrams Set [definition] .Write ( 0X4D006F00640065003A00320000000100000008001E00000032002C0030002C00, Null, 0) Where diagram_id = @newid -- index:7969
  Update sysdiagrams Set [definition] .Write ( 0X3200380034002C0030002C003200320039003500000020000000540061006200, Null, 0) Where diagram_id = @newid -- index:8001
  Update sysdiagrams Set [definition] .Write ( 0X6C00650056006900650077004D006F00640065003A0033000000010000000800, Null, 0) Where diagram_id = @newid -- index:8033
  Update sysdiagrams Set [definition] .Write ( 0X1E00000032002C0030002C003200380034002C0030002C003200320039003500, Null, 0) Where diagram_id = @newid -- index:8065
  Update sysdiagrams Set [definition] .Write ( 0X0000200000005400610062006C00650056006900650077004D006F0064006500, Null, 0) Where diagram_id = @newid -- index:8097
  Update sysdiagrams Set [definition] .Write ( 0X3A00340000000100000008003E00000034002C0030002C003200380034002C00, Null, 0) Where diagram_id = @newid -- index:8129
  Update sysdiagrams Set [definition] .Write ( 0X30002C0032003200390035002C00310032002C0032003700310035002C003100, Null, 0) Where diagram_id = @newid -- index:8161
  Update sysdiagrams Set [definition] .Write ( 0X31002C0031003600360035000000030000000300000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:8193
  Update sysdiagrams Set [definition] .Write ( 0X000000000000D002000006002800000041006300740069007600650054006100, Null, 0) Where diagram_id = @newid -- index:8225
  Update sysdiagrams Set [definition] .Write ( 0X62006C00650056006900650077004D006F006400650000000100000008000400, Null, 0) Where diagram_id = @newid -- index:8257
  Update sysdiagrams Set [definition] .Write ( 0X000031000000200000005400610062006C00650056006900650077004D006F00, Null, 0) Where diagram_id = @newid -- index:8289
  Update sysdiagrams Set [definition] .Write ( 0X640065003A00300000000100000008003A00000034002C0030002C0032003800, Null, 0) Where diagram_id = @newid -- index:8321
  Update sysdiagrams Set [definition] .Write ( 0X34002C0030002C0032003200390035002C0031002C0031003800370035002C00, Null, 0) Where diagram_id = @newid -- index:8353
  Update sysdiagrams Set [definition] .Write ( 0X35002C0031003200340035000000200000005400610062006C00650056006900, Null, 0) Where diagram_id = @newid -- index:8385
  Update sysdiagrams Set [definition] .Write ( 0X650077004D006F00640065003A00310000000100000008001E00000032002C00, Null, 0) Where diagram_id = @newid -- index:8417
  Update sysdiagrams Set [definition] .Write ( 0X30002C003200380034002C0030002C0032003700390030000000200000005400, Null, 0) Where diagram_id = @newid -- index:8449
  Update sysdiagrams Set [definition] .Write ( 0X610062006C00650056006900650077004D006F00640065003A00320000000100, Null, 0) Where diagram_id = @newid -- index:8481
  Update sysdiagrams Set [definition] .Write ( 0X000008001E00000032002C0030002C003200380034002C0030002C0032003200, Null, 0) Where diagram_id = @newid -- index:8513
  Update sysdiagrams Set [definition] .Write ( 0X390035000000200000005400610062006C00650056006900650077004D006F00, Null, 0) Where diagram_id = @newid -- index:8545
  Update sysdiagrams Set [definition] .Write ( 0X640065003A00330000000100000008001E00000032002C0030002C0032003800, Null, 0) Where diagram_id = @newid -- index:8577
  Update sysdiagrams Set [definition] .Write ( 0X34002C0030002C0032003200390035000000200000005400610062006C006500, Null, 0) Where diagram_id = @newid -- index:8609
  Update sysdiagrams Set [definition] .Write ( 0X56006900650077004D006F00640065003A00340000000100000008003E000000, Null, 0) Where diagram_id = @newid -- index:8641
  Update sysdiagrams Set [definition] .Write ( 0X34002C0030002C003200380034002C0030002C0032003200390035002C003100, Null, 0) Where diagram_id = @newid -- index:8673
  Update sysdiagrams Set [definition] .Write ( 0X32002C0032003700310035002C00310031002C00310036003600350000000400, Null, 0) Where diagram_id = @newid -- index:8705
  Update sysdiagrams Set [definition] .Write ( 0X00000400000000000000000000000000000000000000D0020000060028000000, Null, 0) Where diagram_id = @newid -- index:8737
  Update sysdiagrams Set [definition] .Write ( 0X4100630074006900760065005400610062006C00650056006900650077004D00, Null, 0) Where diagram_id = @newid -- index:8769
  Update sysdiagrams Set [definition] .Write ( 0X6F00640065000000010000000800040000003100000020000000540061006200, Null, 0) Where diagram_id = @newid -- index:8801
  Update sysdiagrams Set [definition] .Write ( 0X6C00650056006900650077004D006F00640065003A0030000000010000000800, Null, 0) Where diagram_id = @newid -- index:8833
  Update sysdiagrams Set [definition] .Write ( 0X3A00000034002C0030002C003200380034002C0030002C003200320039003500, Null, 0) Where diagram_id = @newid -- index:8865
  Update sysdiagrams Set [definition] .Write ( 0X2C0031002C0031003800370035002C0035002C00310032003400350000002000, Null, 0) Where diagram_id = @newid -- index:8897
  Update sysdiagrams Set [definition] .Write ( 0X00005400610062006C00650056006900650077004D006F00640065003A003100, Null, 0) Where diagram_id = @newid -- index:8929
  Update sysdiagrams Set [definition] .Write ( 0X00000100000008001E00000032002C0030002C003200380034002C0030002C00, Null, 0) Where diagram_id = @newid -- index:8961
  Update sysdiagrams Set [definition] .Write ( 0X32003700390030000000200000005400610062006C0065005600690065007700, Null, 0) Where diagram_id = @newid -- index:8993
  Update sysdiagrams Set [definition] .Write ( 0X4D006F00640065003A00320000000100000008001E00000032002C0030002C00, Null, 0) Where diagram_id = @newid -- index:9025
  Update sysdiagrams Set [definition] .Write ( 0X3200380034002C0030002C003200320039003500000020000000540061006200, Null, 0) Where diagram_id = @newid -- index:9057
  Update sysdiagrams Set [definition] .Write ( 0X6C00650056006900650077004D006F00640065003A0033000000010000000800, Null, 0) Where diagram_id = @newid -- index:9089
  Update sysdiagrams Set [definition] .Write ( 0X1E00000032002C0030002C003200380034002C0030002C003200320039003500, Null, 0) Where diagram_id = @newid -- index:9121
  Update sysdiagrams Set [definition] .Write ( 0X0000200000005400610062006C00650056006900650077004D006F0064006500, Null, 0) Where diagram_id = @newid -- index:9153
  Update sysdiagrams Set [definition] .Write ( 0X3A00340000000100000008003E00000034002C0030002C003200380034002C00, Null, 0) Where diagram_id = @newid -- index:9185
  Update sysdiagrams Set [definition] .Write ( 0X30002C0032003200390035002C00310032002C0032003700310035002C003100, Null, 0) Where diagram_id = @newid -- index:9217
  Update sysdiagrams Set [definition] .Write ( 0X31002C0031003600360035000000050000000500000000000000460000000101, Null, 0) Where diagram_id = @newid -- index:9249
  Update sysdiagrams Set [definition] .Write ( 0X520001000000640062006F00000046004B005F0053006F006C00640069006500, Null, 0) Where diagram_id = @newid -- index:9281
  Update sysdiagrams Set [definition] .Write ( 0X720057006500610070006F006E0073005F0053006F006C006400690065007200, Null, 0) Where diagram_id = @newid -- index:9313
  Update sysdiagrams Set [definition] .Write ( 0X730000000000000000000000C402000000000600000006000000050000000800, Null, 0) Where diagram_id = @newid -- index:9345
  Update sysdiagrams Set [definition] .Write ( 0X000001778B2440778B240000000000000000AD0F000001000007000000070000, Null, 0) Where diagram_id = @newid -- index:9377
  Update sysdiagrams Set [definition] .Write ( 0X0000000000440000000101520001000000640062006F00000046004B005F0053, Null, 0) Where diagram_id = @newid -- index:9409
  Update sysdiagrams Set [definition] .Write ( 0X006F006C00640069006500720057006500610070006F006E0073005F00570065, Null, 0) Where diagram_id = @newid -- index:9441
  Update sysdiagrams Set [definition] .Write ( 0X00610070006F006E00730000000000000000000000C402000000000800000008, Null, 0) Where diagram_id = @newid -- index:9473
  Update sysdiagrams Set [definition] .Write ( 0X0000000700000008000000017E8B24807E8B240000000000000000AD0F000001, Null, 0) Where diagram_id = @newid -- index:9505
  Update sysdiagrams Set [definition] .Write ( 0X0000090000000900000000000000480000000101520001000000640062006F00, Null, 0) Where diagram_id = @newid -- index:9537
  Update sysdiagrams Set [definition] .Write ( 0X000046004B005F0057006500610070006F006E0073005F005700650061007000, Null, 0) Where diagram_id = @newid -- index:9569
  Update sysdiagrams Set [definition] .Write ( 0X6F006E00430061007400650067006F0072006900650073000000000000000000, Null, 0) Where diagram_id = @newid -- index:9601
  Update sysdiagrams Set [definition] .Write ( 0X0000C402000000000A0000000A0000000900000008000000017A8B24807A8B24, Null, 0) Where diagram_id = @newid -- index:9633
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000AD0F00000100000F00000005000000010000000200000060, Null, 0) Where diagram_id = @newid -- index:9665
  Update sysdiagrams Set [definition] .Write ( 0X0000006500000009000000030000000400000060000000630000000700000004, Null, 0) Where diagram_id = @newid -- index:9697
  Update sysdiagrams Set [definition] .Write ( 0X0000000200000004000000050000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:9729
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:9761
  Update sysdiagrams Set [definition] .Write ( 0X010003000000000000000C0000000B0000004E61BC0000000000000000000000, Null, 0) Where diagram_id = @newid -- index:9793
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:9825
  Update sysdiagrams Set [definition] .Write ( 0XDBE6B0E91C81D011AD5100A0C90F57390000020050044669C57DD00102020000, Null, 0) Where diagram_id = @newid -- index:9857
  Update sysdiagrams Set [definition] .Write ( 0X1048450000000000000000000000000000000000860100004400610074006100, Null, 0) Where diagram_id = @newid -- index:9889
  Update sysdiagrams Set [definition] .Write ( 0X200053006F0075007200630065003D0053004500420041005300540049004500, Null, 0) Where diagram_id = @newid -- index:9921
  Update sysdiagrams Set [definition] .Write ( 0X4E002D00480050005C00530051004C0045005800500052004500530053003200, Null, 0) Where diagram_id = @newid -- index:9953
  Update sysdiagrams Set [definition] .Write ( 0X3000310034003B0049006E0069007400690061006C0020004300610074006100, Null, 0) Where diagram_id = @newid -- index:9985
  Update sysdiagrams Set [definition] .Write ( 0X6C006F0067003D00550053005300410072006D0079003B0049006E0074006500, Null, 0) Where diagram_id = @newid -- index:10017
  Update sysdiagrams Set [definition] .Write ( 0X6700720061007400650064002000530065006300750072006900740079003D00, Null, 0) Where diagram_id = @newid -- index:10049
  Update sysdiagrams Set [definition] .Write ( 0X54007200750065003B004D0075006C007400690070006C006500410063007400, Null, 0) Where diagram_id = @newid -- index:10081
  Update sysdiagrams Set [definition] .Write ( 0X69007600650052006500730075006C00740053006500740073003D0046006100, Null, 0) Where diagram_id = @newid -- index:10113
  Update sysdiagrams Set [definition] .Write ( 0X6C00730065003B005000610063006B00650074002000530069007A0065003D00, Null, 0) Where diagram_id = @newid -- index:10145
  Update sysdiagrams Set [definition] .Write ( 0X34003000390036003B004100700070006C00690063006100740069006F006E00, Null, 0) Where diagram_id = @newid -- index:10177
  Update sysdiagrams Set [definition] .Write ( 0X20004E0061006D0065003D0022004D006900630072006F0073006F0066007400, Null, 0) Where diagram_id = @newid -- index:10209
  Update sysdiagrams Set [definition] .Write ( 0X2000530051004C00200053006500720076006500720020004D0061006E006100, Null, 0) Where diagram_id = @newid -- index:10241
  Update sysdiagrams Set [definition] .Write ( 0X670065006D0065006E0074002000530074007500640069006F00220000000080, Null, 0) Where diagram_id = @newid -- index:10273
  Update sysdiagrams Set [definition] .Write ( 0X050010000000550053005300410072006D007900000000022600120000005300, Null, 0) Where diagram_id = @newid -- index:10305
  Update sysdiagrams Set [definition] .Write ( 0X6F006C0064006900650072007300000008000000640062006F00000000022600, Null, 0) Where diagram_id = @newid -- index:10337
  Update sysdiagrams Set [definition] .Write ( 0X1E00000053006F006C00640069006500720057006500610070006F006E007300, Null, 0) Where diagram_id = @newid -- index:10369
  Update sysdiagrams Set [definition] .Write ( 0X000008000000640062006F000000000226002200000057006500610070006F00, Null, 0) Where diagram_id = @newid -- index:10401
  Update sysdiagrams Set [definition] .Write ( 0X6E00430061007400650067006F00720069006500730000000800000064006200, Null, 0) Where diagram_id = @newid -- index:10433
  Update sysdiagrams Set [definition] .Write ( 0X6F000000000224001000000057006500610070006F006E007300000008000000, Null, 0) Where diagram_id = @newid -- index:10465
  Update sysdiagrams Set [definition] .Write ( 0X640062006F00000001000000D68509B3BB6BF2459AB8371664F0327008004E00, Null, 0) Where diagram_id = @newid -- index:10497
  Update sysdiagrams Set [definition] .Write ( 0X00007B00310036003300340043004400440037002D0030003800380038002D00, Null, 0) Where diagram_id = @newid -- index:10529
  Update sysdiagrams Set [definition] .Write ( 0X34003200450033002D0039004600410032002D00420036004400330032003500, Null, 0) Where diagram_id = @newid -- index:10561
  Update sysdiagrams Set [definition] .Write ( 0X3600330042003900310044007D00000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:10593
  Update sysdiagrams Set [definition] .Write ( 0X010003000000000000000C0000000B0000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:10625
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:10657
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:10689
  Update sysdiagrams Set [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, Null, 0) Where diagram_id = @newid -- index:10721
  Update sysdiagrams Set [definition] .Write ( 0X62885214, Null, 0) Where diagram_id = @newid -- index:10753
 
  Print '=== Finished writing diagram id ' + CAST(@newid AS VARCHAR(100)) + '  ==='
  Print '=== Refresh your Databases-[DbName]-Database Diagrams to see the new diagram ==='
End Try
Begin Catch
  -- If we got here, the [definition] updates didn't complete, so delete the diagram row
  -- (and hope it doesn't fail!)
  DELETE From sysdiagrams
  Where diagram_id = @newid

  Print 'XxXxX ' + Error_Message() + ' XxXxX'
  Print 'XxXxX End Tool_ScriptDiagram2008 -- fix the error before running again XxXxX'

  Return
End Catch
Go